ERROR - 2023-11-20 21:37:38 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ads107\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ads107\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'aluno', Object(SensitiveParameterValue), 'ttoledo', 3306, '', 0)
#1 C:\xampp\htdocs\ads107\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ads107\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ads107\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ads107\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ads107\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ads107\app\Controllers\Pessoa.php(10): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ads107\system\CodeIgniter.php(932): App\Controllers\Pessoa::exibir()
#8 C:\xampp\htdocs\ads107\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pessoa))
#9 C:\xampp\htdocs\ads107\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ads107\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ads107\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ads107\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ads107\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ads107\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ads107\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ads107\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ads107\app\Controllers\Pessoa.php(10): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ads107\system\CodeIgniter.php(932): App\Controllers\Pessoa::exibir()
#7 C:\xampp\htdocs\ads107\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pessoa))
#8 C:\xampp\htdocs\ads107\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ads107\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-11-20 21:37:38 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `pessoas`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Pessoa.php(10): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Pessoa::exibir()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pessoa))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 21:37:58 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ads107\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ads107\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'aluno', Object(SensitiveParameterValue), 'ttoledo', 3306, '', 0)
#1 C:\xampp\htdocs\ads107\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ads107\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ads107\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ads107\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ads107\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ads107\app\Controllers\Pessoa.php(10): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ads107\system\CodeIgniter.php(932): App\Controllers\Pessoa::exibir()
#8 C:\xampp\htdocs\ads107\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pessoa))
#9 C:\xampp\htdocs\ads107\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ads107\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ads107\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ads107\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ads107\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ads107\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ads107\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ads107\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ads107\app\Controllers\Pessoa.php(10): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ads107\system\CodeIgniter.php(932): App\Controllers\Pessoa::exibir()
#7 C:\xampp\htdocs\ads107\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pessoa))
#8 C:\xampp\htdocs\ads107\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ads107\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-11-20 21:37:58 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `pessoas`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Pessoa.php(10): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Pessoa::exibir()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pessoa))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 21:57:51 --> Undefined property: stdClass::$id
in APPPATH\Views\gestores.php on line 133.
 1 APPPATH\Views\gestores.php(133): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$id', 'C:\\xampp\\htdocs\\ads107\\app\\Views\\gestores.php', 133)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\ads107\\app\\Views\\gestores.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('gestores', [], true)
 5 APPPATH\Controllers\Gestor.php(18): view('gestores', [...])
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Gestor::exibir()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestor))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 21:58:58 --> Undefined property: stdClass::$id
in APPPATH\Views\gestores.php on line 134.
 1 APPPATH\Views\gestores.php(134): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$id', 'C:\\xampp\\htdocs\\ads107\\app\\Views\\gestores.php', 134)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\ads107\\app\\Views\\gestores.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('gestores', [], true)
 5 APPPATH\Controllers\Gestor.php(18): view('gestores', [...])
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Gestor::exibir()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestor))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 21:59:24 --> Undefined property: stdClass::$id
in APPPATH\Views\gestores.php on line 134.
 1 APPPATH\Views\gestores.php(134): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$id', 'C:\\xampp\\htdocs\\ads107\\app\\Views\\gestores.php', 134)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\ads107\\app\\Views\\gestores.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('gestores', [], true)
 5 APPPATH\Controllers\Gestor.php(18): view('gestores', [...])
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Gestor::exibir()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestor))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 22:00:30 --> Call to undefined function form_dropdown()
in APPPATH\Views\gestores.php on line 176.
 1 SYSTEMPATH\View\View.php(224): include()
 2 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('gestores', [], true)
 4 APPPATH\Controllers\Gestor.php(18): view('gestores', [...])
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Gestor::exibir()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestor))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 22:00:48 --> Call to undefined function form_dropdown()
in APPPATH\Views\gestores.php on line 176.
 1 SYSTEMPATH\View\View.php(224): include()
 2 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('gestores', [], true)
 4 APPPATH\Controllers\Gestor.php(18): view('gestores', [...])
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Gestor::exibir()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestor))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 22:00:49 --> Call to undefined function form_dropdown()
in APPPATH\Views\gestores.php on line 176.
 1 SYSTEMPATH\View\View.php(224): include()
 2 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('gestores', [], true)
 4 APPPATH\Controllers\Gestor.php(18): view('gestores', [...])
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Gestor::exibir()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestor))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 22:00:49 --> Call to undefined function form_dropdown()
in APPPATH\Views\gestores.php on line 176.
 1 SYSTEMPATH\View\View.php(224): include()
 2 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('gestores', [], true)
 4 APPPATH\Controllers\Gestor.php(18): view('gestores', [...])
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Gestor::exibir()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestor))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 22:00:53 --> Call to undefined function form_dropdown()
in APPPATH\Views\gestores.php on line 176.
 1 SYSTEMPATH\View\View.php(224): include()
 2 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('gestores', [], true)
 4 APPPATH\Controllers\Gestor.php(18): view('gestores', [...])
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Gestor::exibir()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestor))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 22:00:54 --> Call to undefined function form_dropdown()
in APPPATH\Views\gestores.php on line 176.
 1 SYSTEMPATH\View\View.php(224): include()
 2 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('gestores', [], true)
 4 APPPATH\Controllers\Gestor.php(18): view('gestores', [...])
 5 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Gestor::exibir()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestor))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 22:07:09 --> mysqli_sql_exception: Unknown column 'cargo' in 'field list' in C:\xampp\htdocs\ads107\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\ads107\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `am...', 0)
#1 C:\xampp\htdocs\ads107\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `am...')
#2 C:\xampp\htdocs\ads107\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `am...')
#3 C:\xampp\htdocs\ads107\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `am...', Array, false)
#4 C:\xampp\htdocs\ads107\app\Models\ProblemaModel.php(15): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\ads107\app\Controllers\RegisterController.php(15): App\Models\ProblemaModel->insertProblema(Array)
#6 C:\xampp\htdocs\ads107\system\CodeIgniter.php(932): App\Controllers\RegisterController->register()
#7 C:\xampp\htdocs\ads107\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#8 C:\xampp\htdocs\ads107\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ads107\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-11-20 22:07:09 --> Unknown column 'cargo' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `ambiente` (`nome`, `cargo`) VALUES (\'teste\', \'teste\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ambiente` (`nome`, `cargo`) VALUES (\'teste\', \'teste\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ambiente` (`nome`, `cargo`) VALUES (\'teste\', \'teste\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ambiente` (`nome`, `cargo`) VALUES (:nome:, :cargo:)', [...], false)
 5 APPPATH\Models\ProblemaModel.php(15): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\RegisterController.php(15): App\Models\ProblemaModel->insertProblema([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\RegisterController->register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 22:07:32 --> mysqli_sql_exception: Unknown column 'cargo' in 'field list' in C:\xampp\htdocs\ads107\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\ads107\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `am...', 0)
#1 C:\xampp\htdocs\ads107\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `am...')
#2 C:\xampp\htdocs\ads107\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `am...')
#3 C:\xampp\htdocs\ads107\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `am...', Array, false)
#4 C:\xampp\htdocs\ads107\app\Models\ProblemaModel.php(15): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\ads107\app\Controllers\RegisterController.php(15): App\Models\ProblemaModel->insertProblema(Array)
#6 C:\xampp\htdocs\ads107\system\CodeIgniter.php(932): App\Controllers\RegisterController->register()
#7 C:\xampp\htdocs\ads107\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
#8 C:\xampp\htdocs\ads107\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ads107\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-11-20 22:07:32 --> Unknown column 'cargo' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `ambiente` (`nome`, `cargo`) VALUES (\'teste\', \'teste\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ambiente` (`nome`, `cargo`) VALUES (\'teste\', \'teste\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ambiente` (`nome`, `cargo`) VALUES (\'teste\', \'teste\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ambiente` (`nome`, `cargo`) VALUES (:nome:, :cargo:)', [...], false)
 5 APPPATH\Models\ProblemaModel.php(15): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\RegisterController.php(15): App\Models\ProblemaModel->insertProblema([...])
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\RegisterController->register()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegisterController))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
